services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - mysleep-db:/var/lib/postgresql/data

  api:
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    depends_on:
      - db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file: ".env"
    stdin_open: true
    tty: true

volumes:
  mysleep-db:
